spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://121.5.4.166:3306/takeout?useUnicode=true&characterEncoding=utf8
# mail 配置
  mail:
    # SMTP 服务器地址
    host: smtp.163.com
    # 邮件服务器账号
    username: grf0817@163.com
    # 授权码
    password: VBKMOEGIIXAYGOHL
    # 配置端口号（默认使用 25，若项目发布到云服务器，需要开放相应端口 465，需要配置相关 ssl 协议）
    port: 25
    # 编码字符集采用 UTF-8
    default-encoding: UTF-8
    # 配置 ssl 协议（端口为 25 时，可以不用配置）
    #    properties:
    #      mail:
    #        smtp:
    #          ssl:
    #            enable: true
    #          socketFactory:
    #            port: 465
    #            class: javax.net.ssl.SSLSocketFactory
    # 文件上传大小配置（由于附件的存在，可以视项目情况修改）
  servlet:
    multipart:
      # 限制单个文件大小
      max-file-size: 10MB
      # 限制单次请求总文件大小
      max-request-size: 50MB
  # 阿里云配置信息
aliyun:
  # common 配置信息
  accessKeyId: LTAI5tAL58KhVpKhG5fWvyWG
  accessKeySecret: r3IbD9pnRmwMiRW4Gl5aBfjSH0rU69
  # OSS 相关配置信息
  endPoint: http://oss-cn-beijing.aliyuncs.com
  bucketName: admin-vue-templatea
  domain: http://admin-vue-templatea.oss-cn-beijing.aliyuncs.com
server:
  port: 8082